config/routes.rb
Rails.application.routes.draw do
  get 'member/show'

  get 'dashboard/index'

  get 'dashboard/main'

  get 'dashboard/archive'

  resources :comments

  resources :blogposts

  resources :groups

  root "homepage#index"

  get 'homepage/about'

  get 'homepage/index'

  get 'homepage/main'

  get 'homepage/contact'

  get 'homepage/splash'

  get 'blogposts/mass_comment_count'

  devise_for :users

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]
  # GET /blogposts
  # GET /blogposts.json
  before_filter :authenticate_user!

  include BlogpostsHelper
  
  def index
    @blogposts = Blogpost.all
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
  end

  def mass_comment_count
    blogposts = Blogpost.all
    blogposts.each do |blogpost|
      comment_counter blogpost.id
    end
  end


  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      @blogpost.user_id = current_user.id
      if @blogpost.save
        @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy

    @comments = Comment.where(blogpost: @blogpost.id)
      @comments.each do |comment|
        comment.destroy
      end

    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:content, :comment_id, :user_id, :comment_count)
    end
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper

		def comment_counter blogpost_id
		
		blogpost = Blogpost.find(blogpost_id)

		num_comments = Blogpost.find(blogpost_id).comments.count

		blogpost.comment_count = num_comments

		blogpost.save

	end
	
end

app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= current_user.user_name %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <!--
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.number_field :comment_id %>
  </div>
  -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogposts/edit.html.erb
<h1>Editing blogpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', dashboard_index_path %> |
<%= link_to 'Destroy', @blogpost, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/blogposts/index.html.erb
<h1>Listing blogposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogposts.each do |blogpost| %>
      <tr>
        <td><%= blogpost.content %></td>
        <td><%= blogpost.user_id %></td>
        <td><%= link_to 'Show', blogpost %></td>
        <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
        <td><%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogpost', new_blogpost_path %>

app/views/blogposts/mass_comment_count.html.erb
mass_comment_count.html.erb

app/views/blogposts/new.html.erb
<h1>New blogpost</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_index_path %>

app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= current_user.user_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blogpost.content %>
</p>

<!--
<p>
  <strong>Comment:</strong>
  <%= @blogpost.comment_id %>
</p>
-->

<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', dashboard_index_path %> |
<%= link_to 'Destroy', @blogpost, method: :delete, data: { confirm: 'Are you sure?' } %>