config/routes.rb
Rails.application.routes.draw do
  get 'member/show'

  get 'dashboard/index'

  get 'dashboard/main'

  get 'dashboard/archive'

  resources :comments

  resources :blogposts

  resources :groups

  root "homepage#index"

  get 'homepage/about'

  get 'homepage/index'

  get 'homepage/main'

  get 'homepage/contact'

  get 'homepage/splash'

  get 'blogposts/mass_comment_count'

  devise_for :users

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	
  def index
    @blogposts = Blogpost.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
  	@blogposts_total = Blogpost.all
  end

  def main
  	@blogpost_id = params[:blogpost_id]
    @blogpost = Blogpost.where(id: @blogpost_id)

    @comments = Comment.where(blogpost_id: @blogpost_id)
  end

  def archive
  end

  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<center><%= will_paginate @blogposts %></center><br />
<%@blogposts.each do |blogpost|%>
<table class="table table-hover table-condensed">
	<td><b><%=blogpost.user.user_name%></b><br>
	<%=blogpost.content%><br>
	<font size = 1><a href=/dashboard/main/?blogpost_id=<%=blogpost.id%>>Comment (<%="#{blogpost.comment_count}"%>)</a>
	<% if current_user.id == blogpost.user_id%>
		<%= link_to 'Edit', edit_blogpost_path(blogpost) %> | <%=blogpost.created_at%>
	<%else%>
		<%=blogpost.created_at%>
	<%end%>

</font></td>
</table>
<%end%>
<center><%= will_paginate @blogposts %></center>

app/views/dashboard/main.html.erb
<%@blogpost.each do |blogpost|%>
	<table class="table table-hover table-condensed">
	<td><b><%=blogpost.user.user_name%></b><br>
	<%=blogpost.content%><br>
	<font size = 1>
	<% if current_user.id == blogpost.user_id%>
		<%= link_to 'Edit', edit_blogpost_path(blogpost) %> | <%=blogpost.updated_at%>
	<%else%>
		<%=blogpost.updated_at%>
	<%end%>
	</font>
	</table>
<%end%>
<h2>Comments</h3>
<%if @comments.count == 0 %>
	There are no comments to display
<%end%>
<%@comments.each do |comment|%>
	<table class="table table-hover table-condensed">

	<td><b><%=comment.user.user_name%></b><br>
	<%=comment.content%><br>
	<font size = 1>
	<%@blogpost.each do |blogpost|%>
		<% if current_user.id == blogpost.user_id && current_user.id != comment.user_id%>
			<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %> | <%=comment.updated_at%>

		<% elsif current_user.id == comment.user_id %>
			<%= link_to 'Edit', edit_comment_path(comment) %> | <%=comment.updated_at%>

		<%else%>
			<%=comment.updated_at%>
		<%end%>
	<%end%>
	</font>
	</table>
<%end%>
<br>
<br>
<%@blogpost.each do |blogpost|%>
<a href=/comments/new?blogpost_id=<%=blogpost.id%>>New Comment</a>
<%end%>