config/routes.rb
Rails.application.routes.draw do
  get 'member/show'

  get 'dashboard/index'

  get 'dashboard/main'

  get 'dashboard/archive'

  resources :comments

  resources :blogposts

  resources :groups

  root "homepage#index"

  get 'homepage/about'

  get 'homepage/index'

  get 'homepage/main'

  get 'homepage/contact'

  get 'homepage/splash'

  get 'blogposts/mass_comment_count'

  devise_for :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blogpost 
	belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  include BlogpostsHelper
  before_filter :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @blogpost_id = @comment.blogpost_id
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @blogpost_id = params[:blogpost_id]
  end

  # GET /comments/1/edit
  def edit
    @blogpost_id = @comment.blogpost_id
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @blogpost_id = params[:blogpost_id]

    respond_to do |format|

    @comment.user_id = current_user.id

      if @comment.save
        comment_counter @comment.blogpost_id
        @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|

      old_id = @comment.blogpost_id

      if @comment.update(comment_params)

        comment_counter old_id
        comment_counter @comment.blogpost_id

        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy

    blogpost_id = @comment.blogpost_id

    @comment.destroy

    comment_counter blogpost_id

    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }


    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :blogpost_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= current_user.user_name %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area  :content %>
  </div>

  <div class="field">
    <%if params[:blogpost_id] == nil%>
      <%= f.hidden_field :blogpost_id, :value => @blogpost_id %><br>
    <%else%>
      <%= f.hidden_field :blogpost_id, :value => params[:blogpost_id] %><br>
    <%end%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<a href="/dashboard/main/?blogpost_id=<%=@blogpost_id%>">Back</a> |
<%= link_to 'Destroy', @comment, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Blogpost</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.blogpost_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<a href="/dashboard/main/?blogpost_id=<%=@blogpost_id%>">Back</a>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= current_user.user_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<!--
<p>
  <strong>Blogpost:</strong>
  <%= @comment.blogpost_id %>
</p>
-->

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<a href="/dashboard/main/?blogpost_id=<%=@blogpost_id%>">Back</a> |
<%= link_to 'Destroy', @comment, method: :delete, data: { confirm: 'Are you sure?' } %>